
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vencoder"
version = "0.0.1"
authors = [{name = "Coleman Breen", email = "cebreen@wisc.edu"}]
description = "A simple package to encode sequence variation into matrix representations."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/cbreenmachine/vencoder"
Issues = "https://github.com/cbreenmachine/vencoder/issues"

dependencies = [
    "numpy",
    "pandas"
]
